### ISSUE TITLE
ProgrammingError at /auth/login/ relation "django_session" does not exist LINE 1: SELECT (1) AS "a" FROM "django_session" WHERE "django_sessio...

### ISSUE THREAD

**Issue by ParthMaisheri** [uktrade/return-to-office#33]
After installing everything and starting this we get 
`ProgrammingError at /auth/login/
relation "django_session" does not exist
LINE 1: SELECT (1) AS "a" FROM "django_session" WHERE "django_sessio...`

get the same error in 

make shell
import custom_usermodel
me = custom_usermodel.models.User.objects.first()

need help ASAP

**Comment by rossmiller** [comment]
This project is designed to work with our own single sign on. You will need to unpick in order for it to work with other auth mechanisms.
